[package]
name = "poor-mans-4090"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.26", features = ["derive"]}
image = "0.24.5"
nalgebra = "0.31.4"
